using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.IO;
using System.Text;

namespace PWHelper.Elements
{
    public class Config
    {
        public enum ID_SPACE
        {
            ESSENCE = 0,
            ADDON = 1,
            TALK = 2,
            FACE = 3,
            RECIPE = 4,
            CONFIG = 5,
            HOME = 6,
        };

        public enum DATA_TYPE
        {
            DT_INVALID = 0,
            DT_EQUIPMENT_ADDON,
            DT_WEAPON_MAJOR_TYPE,
            DT_WEAPON_SUB_TYPE,
            DT_WEAPON_ESSENCE,

            DT_ARMOR_MAJOR_TYPE,
            DT_ARMOR_SUB_TYPE,
            DT_ARMOR_ESSENCE,
            DT_DECORATION_MAJOR_TYPE,
            DT_DECORATION_SUB_TYPE,

            DT_DECORATION_ESSENCE = 10,
            DT_MEDICINE_MAJOR_TYPE,
            DT_MEDICINE_SUB_TYPE,
            DT_MEDICINE_ESSENCE,
            DT_MATERIAL_MAJOR_TYPE,

            DT_MATERIAL_SUB_TYPE,
            DT_MATERIAL_ESSENCE,
            DT_DAMAGERUNE_SUB_TYPE,
            DT_DAMAGERUNE_ESSENCE,
            DT_ARMORRUNE_SUB_TYPE,

            DT_ARMORRUNE_ESSENCE = 20,
            DT_SKILLTOME_SUB_TYPE,
            DT_SKILLTOME_ESSENCE,
            DT_FLYSWORD_ESSENCE,
            DT_WINGMANWING_ESSENCE,

            DT_TOWNSCROLL_ESSENCE,
            DT_UNIONSCROLL_ESSENCE,
            DT_REVIVESCROLL_ESSENCE,
            DT_ELEMENT_ESSENCE,
            DT_TASKMATTER_ESSENCE,

            DT_TOSSMATTER_ESSENCE = 30,
            DT_PROJECTILE_TYPE,
            DT_PROJECTILE_ESSENCE,
            DT_QUIVER_SUB_TYPE,
            DT_QUIVER_ESSENCE,

            DT_STONE_SUB_TYPE,
            DT_STONE_ESSENCE,
            DT_MONSTER_ADDON,
            DT_MONSTER_TYPE,
            DT_MONSTER_ESSENCE,

            DT_NPC_TALK_SERVICE = 40,
            DT_NPC_SELL_SERVICE,
            DT_NPC_BUY_SERVICE,
            DT_NPC_REPAIR_SERVICE,
            DT_NPC_INSTALL_SERVICE,

            DT_NPC_UNINSTALL_SERVICE,
            DT_NPC_TASK_IN_SERVICE,
            DT_NPC_TASK_OUT_SERVICE,
            DT_NPC_TASK_MATTER_SERVICE,
            DT_NPC_SKILL_SERVICE,

            DT_NPC_HEAL_SERVICE = 50,
            DT_NPC_TRANSMIT_SERVICE,
            DT_NPC_TRANSPORT_SERVICE,
            DT_NPC_PROXY_SERVICE,
            DT_NPC_STORAGE_SERVICE,

            DT_NPC_MAKE_SERVICE,
            DT_NPC_DECOMPOSE_SERVICE,
            DT_NPC_TYPE,
            DT_NPC_ESSENCE,
            DT_TALK_PROC,

            DT_FACE_TEXTURE_ESSENCE = 60,
            DT_FACE_SHAPE_ESSENCE,
            DT_FACE_EMOTION_TYPE,
            DT_FACE_EXPRESSION_ESSENCE,
            DT_FACE_HAIR_ESSENCE,

            DT_FACE_MOUSTACHE_ESSENCE,
            DT_COLORPICKER_ESSENCE,
            DT_CUSTOMIZEDATA_ESSENCE,
            DT_RECIPE_MAJOR_TYPE,
            DT_RECIPE_SUB_TYPE,

            DT_RECIPE_ESSENCE = 70,
            DT_ENEMY_FACTION_CONFIG,
            DT_CHARRACTER_CLASS_CONFIG,
            DT_PARAM_ADJUST_CONFIG,
            DT_PLAYER_ACTION_INFO_CONFIG,

            DT_TASKDICE_ESSENCE = 75,
            DT_TASKNORMALMATTER_ESSENCE,
            DT_FACE_FALING_ESSENCE,
            DT_PLAYER_LEVELEXP_CONFIG,
            DT_MINE_TYPE,

            DT_MINE_ESSENCE = 80,
            DT_NPC_IDENTIFY_SERVICE,
            DT_FASHION_MAJOR_TYPE,
            DT_FASHION_SUB_TYPE,
            DT_FASHION_ESSENCE,

            DT_FACETICKET_MAJOR_TYPE = 85,
            DT_FACETICKET_SUB_TYPE,
            DT_FACETICKET_ESSENCE,
            DT_FACEPILL_MAJOR_TYPE,
            DT_FACEPILL_SUB_TYPE,

            DT_FACEPILL_ESSENCE = 90,
            DT_SUITE_ESSENCE,
            DT_GM_GENERATOR_TYPE,
            DT_GM_GENERATOR_ESSENCE,
            DT_PET_TYPE,

            DT_PET_ESSENCE = 95,
            DT_PET_EGG_ESSENCE,
            DT_PET_FOOD_ESSENCE,
            DT_PET_FACETICKET_ESSENCE,
            DT_FIREWORKS_ESSENCE,

            DT_WAR_TANKCALLIN_ESSENCE = 100,
            DT_NPC_WAR_TOWERBUILD_SERVICE,
            DT_PLAYER_SECONDLEVEL_CONFIG,
            DT_NPC_RESETPROP_SERVICE,
            DT_NPC_PETNAME_SERVICE,

            DT_NPC_PETLEARNSKILL_SERVICE = 105,
            DT_NPC_PETFORGETSKILL_SERVICE,
            DT_SKILLMATTER_ESSENCE,
            DT_REFINE_TICKET_ESSENCE,
            DT_DESTROYING_ESSENCE,

            DT_NPC_EQUIPBIND_SERVICE = 110,
            DT_NPC_EQUIPDESTROY_SERVICE,
            DT_NPC_EQUIPUNDESTROY_SERVICE,
            DT_BIBLE_ESSENCE,
            DT_SPEAKER_ESSENCE,

            DT_AUTOHP_ESSENCE = 115,
            DT_AUTOMP_ESSENCE,
            DT_DOUBLE_EXP_ESSENCE,
            DT_TRANSMITSCROLL_ESSENCE,
            DT_DYE_TICKET_ESSENCE,

            DT_GOBLIN_ESSENCE = 120,
            DT_GOBLIN_EQUIP_TYPE,
            DT_GOBLIN_EQUIP_ESSENCE,
            DT_GOBLIN_EXPPILL_ESSENCE,
            DT_SELL_CERTIFICATE_ESSENCE,

            DT_TARGET_ITEM_ESSENCE = 125,
            DT_LOOK_INFO_ESSENCE,
            DT_UPGRADE_PRODUCTION_CONFIG,
            DT_ACC_STORAGE_BLACKLIST_CONFIG,
            DT_FACE_HAIR_TEXTURE_MAP,

            DT_MULTI_EXP_CONFIG = 130,
            DT_INC_SKILL_ABILITY_ESSENCE,
            DT_GOD_EVIL_CONVERT_CONFIG,
            DT_WEDDING_CONFIG,
            DT_WEDDING_BOOKCARD_ESSENCE,

            DT_WEDDING_INVITECARD_ESSENCE = 135,
            DT_SHARPENER_ESSENCE,
            DT_FACE_THIRDEYE_ESSENCE,
            DT_FACTION_FORTRESS_CONFIG,
            DT_FACTION_BUILDING_SUB_TYPE,

            DT_FACTION_BUILDING_ESSENCE = 140,
            DT_FACTION_MATERIAL_ESSENCE,
            DT_CONGREGATE_ESSENCE,
            DT_ENGRAVE_MAJOR_TYPE,
            DT_ENGRAVE_SUB_TYPE,

            DT_ENGRAVE_ESSENCE = 145,
            DT_NPC_ENGRAVE_SERVICE,
            DT_NPC_RANDPROP_SERVICE,
            DT_RANDPROP_TYPE,
            DT_RANDPROP_ESSENCE,

            DT_WIKI_TABOO_CONFIG = 150,
            DT_FORCE_CONFIG,
            DT_FORCE_TOKEN_ESSENCE,
            DT_NPC_FORCE_SERVICE,
            DT_PLAYER_DEATH_DROP_CONFIG,

            DT_DYNSKILLEQUIP_ESSENCE = 155,
            DT_CONSUME_POINTS_CONFIG,
            DT_ONLINE_AWARDS_CONFIG,
            DT_COUNTRY_CONFIG,
            DT_GM_ACTIVITY_CONFIG,

            DT_FASHION_WEAPON_CONFIG = 160,
            DT_PET_EVOLVE_CONFIG,
            DT_PET_EVOLVED_SKILL_CONFIG,
            DT_MONEY_CONVERTIBLE_ESSENCE,
            DT_STONE_CHANGE_RECIPE_TYPE,

            DT_STONE_CHANGE_RECIPE = 165,
            DT_MERIDIAN_CONFIG,
            DT_PET_EVOLVED_SKILL_RAND_CONFIG,
            DT_AUTOTASK_DISPLAY_CONFIG,
            DT_TOUCH_SHOP_CONFIG,

            DT_TITLE_CONFIG,
            DT_COMPLEX_TITLE_CONFIG,
            DT_MONSTER_SPIRIT_ESSENCE,
            DT_PLAYER_SPIRIT_CONFIG,
            DT_PLAYER_REINCARNATION_CONFIG,

            DT_HISTORY_STAGE_CONFIG,
            DT_HISTORY_ADVANCE_CONFIG,
            DT_AUTOTEAM_CONFIG,
            DT_PLAYER_REALM_CONFIG,
            DT_CHARIOT_CONFIG,

            DT_CHARIOT_WAR_CONFIG,
            DT_POKER_LEVELEXP_CONFIG,
            DT_POKER_SUITE_ESSENCE,
            DT_POKER_DICE_ESSENCE,
            DT_POKER_SUB_TYPE,

            DT_POKER_ESSENCE,
            DT_TOKEN_SHOP_CONFIG,
            DT_SHOP_TOKEN_ESSENCE,
            DT_GT_CONFIG,
            DT_RAND_SHOP_CONFIG,

            DT_PROFIT_TIME_CONFIG,
            DT_FACTION_PVP_CONFIG,
            DT_UNIVERSAL_TOKEN_ESSENCE,
            DT_TASK_LIST_CONFIG,
            DT_TASK_DICE_BY_WEIGHT_CONFIG,

            DT_FASHION_SUITE_ESSENCE,
            DT_FASHION_BEST_COLOR_CONFIG,
            DT_SIGN_AWARD_CONFIG,
            DT_ASTROLABE_ESSENCE,
            DT_ASTROLABE_RANDOM_ADDON_ESSENCE,

            DT_ASTROLABE_INC_INNER_POINT_VALUE_ESSENCE,
            DT_ASTROLABE_INC_EXP_ESSENCE,
            DT_ITEM_PACKAGE_BY_PROFESSION_ESSENCE,
            DT_ASTROLABE_LEVELEXP_CONFIG,
            DT_ASTROLABE_ADDON_RANDOM_CONFIG,

            DT_ASTROLABE_APPEARANCE_CONFIG,
            DT_EQUIP_MAKE_HOLE_CONFIG,
            DT_SOLO_TOWER_CHALLENGE_LEVEL_CONFIG,
            DT_SOLO_TOWER_CHALLENGE_AWARD_PAGE_CONFIG,
            DT_SOLO_TOWER_CHALLENGE_AWARD_LIST_CONFIG,

            DT_SOLO_TOWER_CHALLENGE_SCORE_COST_CONFIG,
            DT_MNFACTION_WAR_CONFIG,
            DT_NPC_CROSS_SERVER_SERVICE,
            DT_FIREWORKS2_ESSENCE,
            DT_FIX_POSITION_TRANSMIT_ESSENCE,

            DT_HOME_CONFIG,
            DT_HOME_PRODUCTS_CONFIG,
            DT_HOME_RESOURCE_PRODUCE_CONFIG,
            DT_HOME_FORMULAS_PRODUCE_RECIPE,
            DT_HOME_FORMULAS_ITEM_ESSENCE,
            DT_HOME_PRODUCE_SERVICE_CONFIG,
            DT_HOME_FACTORY_CONFIG,
            DT_HOME_ITEM_MAJOR_TYPE,
            DT_HOME_ITEM_SUB_TYPE,
            DT_HOME_ITEM_ENTITY,
            DT_HOME_FORMULAS_PRODUCE_MAJOR_TYPE,
            DT_HOME_FORMULAS_PRODUCE_SUB_TYPE,
            DT_HOME_FORMULAS_ITEM_MAJOR_TYPE,
            DT_HOME_FORMULAS_ITEM_SUB_TYPE,
            DT_HOME_STORAGE_TASK_CONFIG,
            DT_WISH_TRIBUTE_ESSENCE,
            DT_RED_PACKET_PAPER_ESSENCE,

            DT_MAX,
        };

        public static Dictionary<DATA_TYPE, ID_SPACE> SpaceList = new Dictionary<DATA_TYPE, ID_SPACE>
        {
            {DATA_TYPE.DT_EQUIPMENT_ADDON, ID_SPACE.ADDON},
            {DATA_TYPE.DT_WEAPON_MAJOR_TYPE, ID_SPACE.ESSENCE},
            {DATA_TYPE.DT_WEAPON_SUB_TYPE, ID_SPACE.ESSENCE},
            {DATA_TYPE.DT_WEAPON_ESSENCE, ID_SPACE.ESSENCE},
            {DATA_TYPE.DT_ARMOR_MAJOR_TYPE, ID_SPACE.ESSENCE},
            {DATA_TYPE.DT_ARMOR_SUB_TYPE, ID_SPACE.ESSENCE},
            {DATA_TYPE.DT_ARMOR_ESSENCE, ID_SPACE.ESSENCE},
            {DATA_TYPE.DT_DECORATION_MAJOR_TYPE, ID_SPACE.ESSENCE},
            {DATA_TYPE.DT_DECORATION_SUB_TYPE, ID_SPACE.ESSENCE},
            {DATA_TYPE.DT_DECORATION_ESSENCE, ID_SPACE.ESSENCE},
            {DATA_TYPE.DT_MEDICINE_MAJOR_TYPE, ID_SPACE.ESSENCE},
            {DATA_TYPE.DT_MEDICINE_SUB_TYPE, ID_SPACE.ESSENCE},
            {DATA_TYPE.DT_MEDICINE_ESSENCE, ID_SPACE.ESSENCE},
            {DATA_TYPE.DT_MATERIAL_MAJOR_TYPE, ID_SPACE.ESSENCE},
            {DATA_TYPE.DT_MATERIAL_SUB_TYPE, ID_SPACE.ESSENCE},
            {DATA_TYPE.DT_MATERIAL_ESSENCE, ID_SPACE.ESSENCE},
            {DATA_TYPE.DT_DAMAGERUNE_SUB_TYPE, ID_SPACE.ESSENCE},
            {DATA_TYPE.DT_DAMAGERUNE_ESSENCE, ID_SPACE.ESSENCE},
            {DATA_TYPE.DT_ARMORRUNE_SUB_TYPE, ID_SPACE.ESSENCE},
            {DATA_TYPE.DT_ARMORRUNE_ESSENCE, ID_SPACE.ESSENCE},
            {DATA_TYPE.DT_SKILLTOME_SUB_TYPE, ID_SPACE.ESSENCE},
            {DATA_TYPE.DT_SKILLTOME_ESSENCE, ID_SPACE.ESSENCE},
            {DATA_TYPE.DT_SHOP_TOKEN_ESSENCE, ID_SPACE.ESSENCE},
            {DATA_TYPE.DT_UNIVERSAL_TOKEN_ESSENCE, ID_SPACE.ESSENCE},
            {DATA_TYPE.DT_FASHION_SUITE_ESSENCE, ID_SPACE.ESSENCE},
            {DATA_TYPE.DT_ASTROLABE_ESSENCE, ID_SPACE.ESSENCE},
            {DATA_TYPE.DT_ASTROLABE_RANDOM_ADDON_ESSENCE, ID_SPACE.ESSENCE},
            {DATA_TYPE.DT_ASTROLABE_INC_INNER_POINT_VALUE_ESSENCE, ID_SPACE.ESSENCE},
            {DATA_TYPE.DT_ASTROLABE_INC_EXP_ESSENCE, ID_SPACE.ESSENCE},
            {DATA_TYPE.DT_ITEM_PACKAGE_BY_PROFESSION_ESSENCE, ID_SPACE.ESSENCE},
            {DATA_TYPE.DT_FACTION_BUILDING_SUB_TYPE, ID_SPACE.ESSENCE},
            {DATA_TYPE.DT_FACTION_BUILDING_ESSENCE, ID_SPACE.ESSENCE},
            {DATA_TYPE.DT_FACTION_MATERIAL_ESSENCE, ID_SPACE.ESSENCE},
            {DATA_TYPE.DT_FLYSWORD_ESSENCE, ID_SPACE.ESSENCE},
            {DATA_TYPE.DT_WINGMANWING_ESSENCE, ID_SPACE.ESSENCE},
            {DATA_TYPE.DT_TOWNSCROLL_ESSENCE, ID_SPACE.ESSENCE},
            {DATA_TYPE.DT_TRANSMITSCROLL_ESSENCE, ID_SPACE.ESSENCE},
            {DATA_TYPE.DT_UNIONSCROLL_ESSENCE, ID_SPACE.ESSENCE},
            {DATA_TYPE.DT_REVIVESCROLL_ESSENCE, ID_SPACE.ESSENCE},
            {DATA_TYPE.DT_ELEMENT_ESSENCE, ID_SPACE.ESSENCE},
            {DATA_TYPE.DT_TASKMATTER_ESSENCE, ID_SPACE.ESSENCE},
            {DATA_TYPE.DT_TOSSMATTER_ESSENCE, ID_SPACE.ESSENCE},
            {DATA_TYPE.DT_PROJECTILE_TYPE, ID_SPACE.ESSENCE},
            {DATA_TYPE.DT_PROJECTILE_ESSENCE, ID_SPACE.ESSENCE},
            {DATA_TYPE.DT_QUIVER_SUB_TYPE, ID_SPACE.ESSENCE},
            {DATA_TYPE.DT_QUIVER_ESSENCE, ID_SPACE.ESSENCE},
            {DATA_TYPE.DT_STONE_SUB_TYPE, ID_SPACE.ESSENCE},
            {DATA_TYPE.DT_STONE_ESSENCE, ID_SPACE.ESSENCE},
            {DATA_TYPE.DT_MONSTER_ADDON, ID_SPACE.ADDON},
            {DATA_TYPE.DT_MONSTER_TYPE, ID_SPACE.ESSENCE},
            {DATA_TYPE.DT_MONSTER_ESSENCE, ID_SPACE.ESSENCE},
            {DATA_TYPE.DT_NPC_TALK_SERVICE, ID_SPACE.ESSENCE},
            {DATA_TYPE.DT_NPC_SELL_SERVICE, ID_SPACE.ESSENCE},
            {DATA_TYPE.DT_NPC_BUY_SERVICE, ID_SPACE.ESSENCE},
            {DATA_TYPE.DT_NPC_REPAIR_SERVICE, ID_SPACE.ESSENCE},
            {DATA_TYPE.DT_NPC_INSTALL_SERVICE, ID_SPACE.ESSENCE},
            {DATA_TYPE.DT_NPC_UNINSTALL_SERVICE, ID_SPACE.ESSENCE},
            {DATA_TYPE.DT_NPC_TASK_IN_SERVICE, ID_SPACE.ESSENCE},
            {DATA_TYPE.DT_NPC_TASK_OUT_SERVICE, ID_SPACE.ESSENCE},
            {DATA_TYPE.DT_NPC_TASK_MATTER_SERVICE, ID_SPACE.ESSENCE},
            {DATA_TYPE.DT_NPC_SKILL_SERVICE, ID_SPACE.ESSENCE},
            {DATA_TYPE.DT_NPC_HEAL_SERVICE, ID_SPACE.ESSENCE},
            {DATA_TYPE.DT_NPC_TRANSMIT_SERVICE, ID_SPACE.ESSENCE},
            {DATA_TYPE.DT_NPC_TRANSPORT_SERVICE, ID_SPACE.ESSENCE},
            {DATA_TYPE.DT_NPC_PROXY_SERVICE, ID_SPACE.ESSENCE},
            {DATA_TYPE.DT_NPC_STORAGE_SERVICE, ID_SPACE.ESSENCE},
            {DATA_TYPE.DT_NPC_MAKE_SERVICE, ID_SPACE.ESSENCE},
            {DATA_TYPE.DT_NPC_DECOMPOSE_SERVICE, ID_SPACE.ESSENCE},
            {DATA_TYPE.DT_NPC_TYPE, ID_SPACE.ESSENCE},
            {DATA_TYPE.DT_NPC_ESSENCE, ID_SPACE.ESSENCE},
            {DATA_TYPE.DT_TALK_PROC, ID_SPACE.TALK},
            {DATA_TYPE.DT_FACE_TEXTURE_ESSENCE, ID_SPACE.FACE},
            {DATA_TYPE.DT_FACE_SHAPE_ESSENCE, ID_SPACE.FACE},
            {DATA_TYPE.DT_FACE_EMOTION_TYPE, ID_SPACE.FACE},
            {DATA_TYPE.DT_FACE_EXPRESSION_ESSENCE, ID_SPACE.FACE},
            {DATA_TYPE.DT_FACE_HAIR_ESSENCE, ID_SPACE.FACE},
            {DATA_TYPE.DT_FACE_MOUSTACHE_ESSENCE, ID_SPACE.FACE},
            {DATA_TYPE.DT_COLORPICKER_ESSENCE, ID_SPACE.FACE},
            {DATA_TYPE.DT_CUSTOMIZEDATA_ESSENCE, ID_SPACE.FACE},
            {DATA_TYPE.DT_RECIPE_MAJOR_TYPE, ID_SPACE.RECIPE},
            {DATA_TYPE.DT_RECIPE_SUB_TYPE, ID_SPACE.RECIPE},
            {DATA_TYPE.DT_RECIPE_ESSENCE, ID_SPACE.RECIPE},
            {DATA_TYPE.DT_ENGRAVE_MAJOR_TYPE, ID_SPACE.RECIPE},
            {DATA_TYPE.DT_ENGRAVE_SUB_TYPE, ID_SPACE.RECIPE},
            {DATA_TYPE.DT_ENGRAVE_ESSENCE, ID_SPACE.RECIPE},
            {DATA_TYPE.DT_RANDPROP_TYPE, ID_SPACE.RECIPE},
            {DATA_TYPE.DT_RANDPROP_ESSENCE, ID_SPACE.RECIPE},
            {DATA_TYPE.DT_STONE_CHANGE_RECIPE_TYPE, ID_SPACE.RECIPE},
            {DATA_TYPE.DT_STONE_CHANGE_RECIPE, ID_SPACE.RECIPE},
            {DATA_TYPE.DT_ENEMY_FACTION_CONFIG, ID_SPACE.CONFIG},
            {DATA_TYPE.DT_CHARRACTER_CLASS_CONFIG, ID_SPACE.CONFIG},
            {DATA_TYPE.DT_PARAM_ADJUST_CONFIG, ID_SPACE.CONFIG},
            {DATA_TYPE.DT_PLAYER_ACTION_INFO_CONFIG, ID_SPACE.CONFIG},
            {DATA_TYPE.DT_UPGRADE_PRODUCTION_CONFIG, ID_SPACE.CONFIG},
            {DATA_TYPE.DT_ACC_STORAGE_BLACKLIST_CONFIG, ID_SPACE.CONFIG},
            {DATA_TYPE.DT_PLAYER_DEATH_DROP_CONFIG, ID_SPACE.CONFIG},
            {DATA_TYPE.DT_CONSUME_POINTS_CONFIG, ID_SPACE.CONFIG},
            {DATA_TYPE.DT_ONLINE_AWARDS_CONFIG, ID_SPACE.CONFIG},
            {DATA_TYPE.DT_PET_EVOLVE_CONFIG, ID_SPACE.CONFIG},
            {DATA_TYPE.DT_PET_EVOLVED_SKILL_CONFIG, ID_SPACE.CONFIG},
            {DATA_TYPE.DT_PET_EVOLVED_SKILL_RAND_CONFIG, ID_SPACE.CONFIG},
            {DATA_TYPE.DT_AUTOTASK_DISPLAY_CONFIG, ID_SPACE.CONFIG},
            {DATA_TYPE.DT_PLAYER_SPIRIT_CONFIG, ID_SPACE.CONFIG},
            {DATA_TYPE.DT_HISTORY_STAGE_CONFIG, ID_SPACE.CONFIG},
            {DATA_TYPE.DT_HISTORY_ADVANCE_CONFIG, ID_SPACE.CONFIG},
            {DATA_TYPE.DT_AUTOTEAM_CONFIG, ID_SPACE.CONFIG},
            {DATA_TYPE.DT_CHARIOT_CONFIG, ID_SPACE.CONFIG},
            {DATA_TYPE.DT_CHARIOT_WAR_CONFIG, ID_SPACE.CONFIG},
            {DATA_TYPE.DT_POKER_LEVELEXP_CONFIG, ID_SPACE.CONFIG},
            {DATA_TYPE.DT_GT_CONFIG, ID_SPACE.CONFIG},
            {DATA_TYPE.DT_MERIDIAN_CONFIG, ID_SPACE.CONFIG},
            {DATA_TYPE.DT_MONEY_CONVERTIBLE_ESSENCE, ID_SPACE.ESSENCE},
            {DATA_TYPE.DT_FASHION_WEAPON_CONFIG, ID_SPACE.CONFIG},
            {DATA_TYPE.DT_MULTI_EXP_CONFIG, ID_SPACE.CONFIG},
            {DATA_TYPE.DT_WEDDING_CONFIG, ID_SPACE.CONFIG},
            {DATA_TYPE.DT_GOD_EVIL_CONVERT_CONFIG, ID_SPACE.CONFIG},
            {DATA_TYPE.DT_WIKI_TABOO_CONFIG, ID_SPACE.CONFIG},
            {DATA_TYPE.DT_TASKDICE_ESSENCE, ID_SPACE.ESSENCE},
            {DATA_TYPE.DT_POKER_DICE_ESSENCE, ID_SPACE.ESSENCE},
            {DATA_TYPE.DT_TASKNORMALMATTER_ESSENCE, ID_SPACE.ESSENCE},
            {DATA_TYPE.DT_FACE_FALING_ESSENCE, ID_SPACE.FACE},
            {DATA_TYPE.DT_FACE_THIRDEYE_ESSENCE, ID_SPACE.FACE},
            {DATA_TYPE.DT_PLAYER_LEVELEXP_CONFIG, ID_SPACE.CONFIG},
            {DATA_TYPE.DT_ASTROLABE_LEVELEXP_CONFIG, ID_SPACE.CONFIG},
            {DATA_TYPE.DT_ASTROLABE_ADDON_RANDOM_CONFIG, ID_SPACE.CONFIG},
            {DATA_TYPE.DT_ASTROLABE_APPEARANCE_CONFIG, ID_SPACE.CONFIG},
            {DATA_TYPE.DT_EQUIP_MAKE_HOLE_CONFIG, ID_SPACE.CONFIG},
            {DATA_TYPE.DT_SOLO_TOWER_CHALLENGE_LEVEL_CONFIG, ID_SPACE.CONFIG},
            {DATA_TYPE.DT_SOLO_TOWER_CHALLENGE_AWARD_PAGE_CONFIG, ID_SPACE.CONFIG},
            {DATA_TYPE.DT_SOLO_TOWER_CHALLENGE_AWARD_LIST_CONFIG, ID_SPACE.CONFIG},
            {DATA_TYPE.DT_SOLO_TOWER_CHALLENGE_SCORE_COST_CONFIG, ID_SPACE.CONFIG},
            {DATA_TYPE.DT_MNFACTION_WAR_CONFIG, ID_SPACE.CONFIG},
            {DATA_TYPE.DT_FACTION_FORTRESS_CONFIG, ID_SPACE.CONFIG},
            {DATA_TYPE.DT_FORCE_CONFIG, ID_SPACE.CONFIG},
            {DATA_TYPE.DT_COUNTRY_CONFIG, ID_SPACE.CONFIG},
            {DATA_TYPE.DT_GM_ACTIVITY_CONFIG, ID_SPACE.CONFIG},
            {DATA_TYPE.DT_TOUCH_SHOP_CONFIG, ID_SPACE.CONFIG},
            {DATA_TYPE.DT_TOKEN_SHOP_CONFIG, ID_SPACE.CONFIG},
            {DATA_TYPE.DT_RAND_SHOP_CONFIG, ID_SPACE.CONFIG},
            {DATA_TYPE.DT_PROFIT_TIME_CONFIG, ID_SPACE.CONFIG},
            {DATA_TYPE.DT_FACTION_PVP_CONFIG, ID_SPACE.CONFIG},
            {DATA_TYPE.DT_TASK_LIST_CONFIG, ID_SPACE.CONFIG},
            {DATA_TYPE.DT_TASK_DICE_BY_WEIGHT_CONFIG, ID_SPACE.CONFIG},
            {DATA_TYPE.DT_FASHION_BEST_COLOR_CONFIG, ID_SPACE.CONFIG},
            {DATA_TYPE.DT_SIGN_AWARD_CONFIG, ID_SPACE.CONFIG},
            {DATA_TYPE.DT_TITLE_CONFIG, ID_SPACE.CONFIG},
            {DATA_TYPE.DT_COMPLEX_TITLE_CONFIG, ID_SPACE.CONFIG},
            {DATA_TYPE.DT_MINE_TYPE, ID_SPACE.ESSENCE},
            {DATA_TYPE.DT_MINE_ESSENCE, ID_SPACE.ESSENCE},
            {DATA_TYPE.DT_NPC_IDENTIFY_SERVICE, ID_SPACE.ESSENCE},
            {DATA_TYPE.DT_FASHION_MAJOR_TYPE, ID_SPACE.ESSENCE},
            {DATA_TYPE.DT_FASHION_SUB_TYPE, ID_SPACE.ESSENCE},
            {DATA_TYPE.DT_FASHION_ESSENCE, ID_SPACE.ESSENCE},
            {DATA_TYPE.DT_POKER_SUB_TYPE, ID_SPACE.ESSENCE},
            {DATA_TYPE.DT_POKER_ESSENCE, ID_SPACE.ESSENCE},
            {DATA_TYPE.DT_FACETICKET_MAJOR_TYPE, ID_SPACE.ESSENCE},
            {DATA_TYPE.DT_FACETICKET_SUB_TYPE, ID_SPACE.ESSENCE},
            {DATA_TYPE.DT_FACETICKET_ESSENCE, ID_SPACE.ESSENCE},
            {DATA_TYPE.DT_FACEPILL_MAJOR_TYPE, ID_SPACE.ESSENCE},
            {DATA_TYPE.DT_FACEPILL_SUB_TYPE, ID_SPACE.ESSENCE},
            {DATA_TYPE.DT_FACEPILL_ESSENCE, ID_SPACE.ESSENCE},
            {DATA_TYPE.DT_SUITE_ESSENCE, ID_SPACE.ESSENCE},
            {DATA_TYPE.DT_POKER_SUITE_ESSENCE, ID_SPACE.ESSENCE},
            {DATA_TYPE.DT_GM_GENERATOR_TYPE, ID_SPACE.ESSENCE},
            {DATA_TYPE.DT_GM_GENERATOR_ESSENCE, ID_SPACE.ESSENCE},
            {DATA_TYPE.DT_PET_TYPE, ID_SPACE.ESSENCE},
            {DATA_TYPE.DT_PET_ESSENCE, ID_SPACE.ESSENCE},
            {DATA_TYPE.DT_PET_EGG_ESSENCE, ID_SPACE.ESSENCE},
            {DATA_TYPE.DT_PET_FOOD_ESSENCE, ID_SPACE.ESSENCE},
            {DATA_TYPE.DT_PET_FACETICKET_ESSENCE, ID_SPACE.ESSENCE},
            {DATA_TYPE.DT_FIREWORKS_ESSENCE, ID_SPACE.ESSENCE},
            {DATA_TYPE.DT_FIREWORKS2_ESSENCE, ID_SPACE.ESSENCE},
            {DATA_TYPE.DT_FIX_POSITION_TRANSMIT_ESSENCE, ID_SPACE.ESSENCE},
            {DATA_TYPE.DT_GOBLIN_ESSENCE, ID_SPACE.ESSENCE},
            {DATA_TYPE.DT_GOBLIN_EQUIP_TYPE, ID_SPACE.ESSENCE},
            {DATA_TYPE.DT_GOBLIN_EQUIP_ESSENCE, ID_SPACE.ESSENCE},
            {DATA_TYPE.DT_GOBLIN_EXPPILL_ESSENCE, ID_SPACE.ESSENCE},
            {DATA_TYPE.DT_SELL_CERTIFICATE_ESSENCE, ID_SPACE.ESSENCE},
            {DATA_TYPE.DT_TARGET_ITEM_ESSENCE, ID_SPACE.ESSENCE},
            {DATA_TYPE.DT_LOOK_INFO_ESSENCE, ID_SPACE.ESSENCE},
            {DATA_TYPE.DT_WAR_TANKCALLIN_ESSENCE, ID_SPACE.ESSENCE},
            {DATA_TYPE.DT_NPC_WAR_TOWERBUILD_SERVICE, ID_SPACE.ESSENCE},
            {DATA_TYPE.DT_PLAYER_SECONDLEVEL_CONFIG, ID_SPACE.CONFIG},
            {DATA_TYPE.DT_PLAYER_REINCARNATION_CONFIG, ID_SPACE.CONFIG},
            {DATA_TYPE.DT_PLAYER_REALM_CONFIG, ID_SPACE.CONFIG},
            {DATA_TYPE.DT_NPC_RESETPROP_SERVICE, ID_SPACE.ESSENCE},
            {DATA_TYPE.DT_NPC_PETNAME_SERVICE, ID_SPACE.ESSENCE},
            {DATA_TYPE.DT_NPC_PETLEARNSKILL_SERVICE, ID_SPACE.ESSENCE},
            {DATA_TYPE.DT_NPC_PETFORGETSKILL_SERVICE, ID_SPACE.ESSENCE},
            {DATA_TYPE.DT_SKILLMATTER_ESSENCE, ID_SPACE.ESSENCE},
            {DATA_TYPE.DT_DYNSKILLEQUIP_ESSENCE, ID_SPACE.ESSENCE},
            {DATA_TYPE.DT_INC_SKILL_ABILITY_ESSENCE, ID_SPACE.ESSENCE},
            {DATA_TYPE.DT_WEDDING_BOOKCARD_ESSENCE, ID_SPACE.ESSENCE},
            {DATA_TYPE.DT_WEDDING_INVITECARD_ESSENCE, ID_SPACE.ESSENCE},
            {DATA_TYPE.DT_SHARPENER_ESSENCE, ID_SPACE.ESSENCE},
            {DATA_TYPE.DT_CONGREGATE_ESSENCE, ID_SPACE.ESSENCE},
            {DATA_TYPE.DT_MONSTER_SPIRIT_ESSENCE, ID_SPACE.ESSENCE},
            {DATA_TYPE.DT_DESTROYING_ESSENCE, ID_SPACE.ESSENCE},
            {DATA_TYPE.DT_DOUBLE_EXP_ESSENCE, ID_SPACE.ESSENCE},
            {DATA_TYPE.DT_DYE_TICKET_ESSENCE, ID_SPACE.ESSENCE},
            {DATA_TYPE.DT_REFINE_TICKET_ESSENCE, ID_SPACE.ESSENCE},
            {DATA_TYPE.DT_NPC_EQUIPBIND_SERVICE, ID_SPACE.ESSENCE},
            {DATA_TYPE.DT_NPC_EQUIPDESTROY_SERVICE, ID_SPACE.ESSENCE},
            {DATA_TYPE.DT_NPC_EQUIPUNDESTROY_SERVICE, ID_SPACE.ESSENCE},
            {DATA_TYPE.DT_NPC_ENGRAVE_SERVICE, ID_SPACE.ESSENCE},
            {DATA_TYPE.DT_NPC_RANDPROP_SERVICE, ID_SPACE.ESSENCE},
            {DATA_TYPE.DT_NPC_FORCE_SERVICE, ID_SPACE.ESSENCE},
            {DATA_TYPE.DT_NPC_CROSS_SERVER_SERVICE, ID_SPACE.ESSENCE},
            {DATA_TYPE.DT_BIBLE_ESSENCE, ID_SPACE.ESSENCE},
            {DATA_TYPE.DT_SPEAKER_ESSENCE, ID_SPACE.ESSENCE},
            {DATA_TYPE.DT_AUTOHP_ESSENCE, ID_SPACE.ESSENCE},
            {DATA_TYPE.DT_AUTOMP_ESSENCE, ID_SPACE.ESSENCE},
            {DATA_TYPE.DT_FORCE_TOKEN_ESSENCE, ID_SPACE.ESSENCE},
            {DATA_TYPE.DT_FACE_HAIR_TEXTURE_MAP, ID_SPACE.FACE},
            {DATA_TYPE.DT_HOME_CONFIG, ID_SPACE.CONFIG},
            {DATA_TYPE.DT_HOME_PRODUCTS_CONFIG, ID_SPACE.CONFIG},
            {DATA_TYPE.DT_HOME_RESOURCE_PRODUCE_CONFIG, ID_SPACE.CONFIG},
            {DATA_TYPE.DT_HOME_FORMULAS_PRODUCE_RECIPE, ID_SPACE.RECIPE},
            {DATA_TYPE.DT_HOME_FORMULAS_ITEM_ESSENCE, ID_SPACE.ESSENCE},
            {DATA_TYPE.DT_HOME_PRODUCE_SERVICE_CONFIG, ID_SPACE.CONFIG},
            {DATA_TYPE.DT_HOME_FACTORY_CONFIG, ID_SPACE.CONFIG},
            {DATA_TYPE.DT_HOME_ITEM_MAJOR_TYPE, ID_SPACE.HOME},
            {DATA_TYPE.DT_HOME_ITEM_SUB_TYPE, ID_SPACE.HOME},
            {DATA_TYPE.DT_HOME_ITEM_ENTITY, ID_SPACE.HOME},
            {DATA_TYPE.DT_HOME_FORMULAS_PRODUCE_MAJOR_TYPE, ID_SPACE.HOME},
            {DATA_TYPE.DT_HOME_FORMULAS_PRODUCE_SUB_TYPE, ID_SPACE.HOME},
            {DATA_TYPE.DT_HOME_FORMULAS_ITEM_MAJOR_TYPE, ID_SPACE.HOME},
            {DATA_TYPE.DT_HOME_FORMULAS_ITEM_SUB_TYPE, ID_SPACE.HOME},
            {DATA_TYPE.DT_HOME_STORAGE_TASK_CONFIG, ID_SPACE.CONFIG},
            {DATA_TYPE.DT_WISH_TRIBUTE_ESSENCE, ID_SPACE.ESSENCE},
            {DATA_TYPE.DT_RED_PACKET_PAPER_ESSENCE, ID_SPACE.ESSENCE}
        };

        public class ConfigList
        {
            public int Id { get; set; }
            public string Empty { get; set; }
            public string Name { get; set; }
            public ID_SPACE Space { get; set; }
            public string Offset { get; set; }
            public string[] Fields { get; set; }
            public string[] Types { get; set; }
            public int Size { get; set; }
            public int CountItems { get; set; }
            public byte[] Data { get; set; }
        }

        public static int Count;
        public static int Dialog;
        public static ObservableCollection<ConfigList> Lists = new ObservableCollection<ConfigList>();

        public static ID_SPACE DataTypeToSpace(DATA_TYPE dt) => SpaceList.ContainsKey(dt) ? SpaceList[dt] : ID_SPACE.ESSENCE;
        
        public static void Load(short version)
        {
            using var sr = new StreamReader($"configs/{version}.cfg");
            Count = Convert.ToInt32(sr.ReadLine());
            Dialog = Convert.ToInt32(sr.ReadLine());

            for (var i = 0; i < Count; i++)
            {
                var list = new ConfigList
                {
                    Id = i,
                    Empty = sr.ReadLine(),
                    Name = sr.ReadLine(),
                    Space = DataTypeToSpace((DATA_TYPE) i),
                    Offset = sr.ReadLine(),
                    Fields = sr.ReadLine()?.Split(";"),
                    Types = sr.ReadLine()?.Split(";")
                };

                if (list.Types == null) continue;
                foreach (var type in list.Types)
                    list.Size += GetSize(type);

                Lists.Add(list);
            }
        }

        private static int GetSize(string field)
        {
            if (field == "int16") return 2;
            if (field == "int32") return 4;
            if (field == "int64") return 8;
            if (field == "float") return 4;
            if (field.Contains("wstring:")) return Convert.ToInt32(field.Substring(8));
            if (field.Contains("string:")) return Convert.ToInt32(field.Substring(7));
            return 0;
        }
    }
}